
### Create a new book
POST http://localhost:8000/users
Content-Type: application/json

{
    "firstName": "John",
    "lastName": "Doe",
    "email":"chihab.mg.me@gmail.com",
    "password":"password",
    "passwordConfirmation":"password",
    "userType":"USER"
}
