version: "3.8"
services:
  # Build client first
  client:
    build:
      context: ./apps/client
    container_name: eventify-client-builder
    volumes:
      - client-build:/app/dist
    # Command to exit after build completes
    command: ["echo", "Client build completed"]
    # This ensures the container stops after building
    restart: "no"
    env_file:
      - .env

  # Nginx depends on client build
  nginx:
    image: nginx:stable-alpine
    container_name: eventify-nginx
    ports:
      - "8888:80"
    volumes:
      - "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
      - client-build:/usr/share/nginx/html:ro
    depends_on:
      - client

  # Backend API
  backend:
    build:
      context: ./apps/api
    container_name: eventify-api
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - nginx

# Named volume for sharing build files between containers
volumes:
  client-build:

