version: "3.8"

services:
  client:
    image: chihabs/eventify-client:latest
    restart: no
    build:
      context : ./apps/client
      args:
        - VITE_API_URL=${VITE_API_URL}  
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env


  backend:
    image: chihabs/eventify-api:latest
    restart: always
    build:
      context : ./apps/api
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}

  nginx:
    image: chihabs/eventify-nginx:latest
    build:
      context : ./nginx
      dockerfile: Dockerfile.prod
    container_name: eventify-nginx
    restart: always
    # ports:
    #   - "80:80" # comatedc 
    depends_on:
      - backend
