version: "3.8"
services:
  # Build client first
  client:
    build:
      context: ./apps/client
      args:
        - VITE_API_URL=${VITE_API_URL}  
    container_name: eventify-client-builder
      #volumes:
      #- "./volumes/dist:/app/dist"  # Map the dist directory
    command: ["echo", "Client build completed"]
    restart: "no"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    env_file:
      - .env

  # Nginx depends on client build
  nginx:
    #image: nginx:stable-alpine
    build:
      context: ./nginx
      dockerfile: Dockerfile

    container_name: eventify-nginx
    ports:
      - "8888:80"
        #    volumes:
        #- "./nginx/nginx.conf:/etc/nginx/nginx.conf:ro"
        #- "./volumes/dist:/usr/share/nginx/html"  # Serve build files from dist
    depends_on:
      - client
      - backend

  # Backend API
  backend:
    build:
      context: ./apps/api
    container_name: eventify-api
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - CLIENT_URL=${CLIENT_URL}
      - RESEND_API_KEY=${RESEND_API_KEY}
      - EMAIL_FROM=${EMAIL_FROM}

