
FROM chihabs:eventify-client AS client_build_assets

FROM nginx:stable-alpine
COPY --from=client_build_assets /app/dist /usr/share/nginx/html/
COPY nginx.conf /etc/nginx/nginx.conf

EXPOSE 80

CMD ["nginx","-g","daemon off;"]

